name: Ruby

on:
  pull_request:
    branches: ['*']
  push:
    branches: [main]

jobs:
  test:

    runs-on: ubuntu-latest

    services:
      # Label used to access the service container
      mysql:
        # Docker Hub image and tag
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: my-secret-password
          MYSQL_DATABASE: fidelity_plan_test #replace with name
          MYSQL_USER: test_user
          MYSQL_PASSWORD: password
        # Set health checks to wait until mysql has started
        options: >-
          --health-cmd "mysqladmin ping -h localhost -u root -p$$MYSQL_ROOT_PASSWORD"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@473e4d8fe5dd94ee328fdfca9f8c9c7afc9dae5e
        with:
          ruby-version: 2.6.7
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Setup test database
        run: bin/rails db:setup
        env:
          DATABASE_URL: mysql2://test_user:password@127.0.0.1:3306/fidelity_plan_test

      - name: Install Webpacker
        run: bin/rails webpacker:install

      - name: Run tests
        run: bundle exec rake